import type { ComponentType } from 'react';

import {
  MeshGradient,
  meshGradientPresets,
  SmokeRing,
  smokeRingPresets,
  NeuroNoise,
  neuroNoisePresets,
  DotOrbit,
  dotOrbitPresets,
  DotGrid,
  dotGridPresets,
  SimplexNoise,
  simplexNoisePresets,
  Metaballs,
  metaballsPresets,
  Waves,
  wavesPresets,
  PerlinNoise,
  perlinNoisePresets,
  Voronoi,
  voronoiPresets,
  Warp,
  warpPresets,
  GodRays,
  godRaysPresets,
  Spiral,
  spiralPresets,
  Swirl,
  swirlPresets,
  Dithering,
  ditheringPresets,
  GrainGradient,
  grainGradientPresets,
  PulsingBorder,
  pulsingBorderPresets,
  ColorPanels,
  colorPanelsPresets,
  StaticMeshGradient,
  staticMeshGradientPresets,
  StaticRadialGradient,
  staticRadialGradientPresets,
  PaperTexture,
  paperTexturePresets,
  Water,
  waterPresets,
  FlutedGlass,
  flutedGlassPresets,
  ImageDithering,
  imageDitheringPresets,
  Heatmap,
  heatmapPresets,
  Bloom,
  bloomPresets,
  LiquidMetal,
  liquidMetalPresets,
  HalftoneDots,
  halftoneDotsPresets,
  HalftoneCmyk,
  halftoneCmykPresets,
} from '@paper-design/shaders-react';

// --- Param config types ---

export type ParamType = 'number' | 'color' | 'colorArray' | 'select' | 'boolean';

interface BaseParam {
  key: string;
  label: string;
  type: ParamType;
}

export interface NumberParam extends BaseParam {
  type: 'number';
  min: number;
  max: number;
  step: number;
}

export interface ColorParam extends BaseParam {
  type: 'color';
}

export interface ColorArrayParam extends BaseParam {
  type: 'colorArray';
  maxColors: number;
}

export interface SelectParam extends BaseParam {
  type: 'select';
  options: string[];
}

export interface BooleanParam extends BaseParam {
  type: 'boolean';
}

export type ParamConfig = NumberParam | ColorParam | ColorArrayParam | SelectParam | BooleanParam;

// --- Shader entry ---

export interface ShaderEntry {
  name: string;
  slug: string;
  Component: ComponentType<any>;
  presets: Array<{ name: string; params: Record<string, any> }>;
  requiresImage: boolean;
  params: ParamConfig[];
}

// --- Shared param builders ---

const speed = (max = 10): NumberParam => ({ key: 'speed', label: 'Speed', type: 'number', min: 0, max, step: 0.1 });
const fit: SelectParam = { key: 'fit', label: 'Fit', type: 'select', options: ['none', 'contain', 'cover', 'square'] };
const scaleSizing = (min = 0.01, max = 4): NumberParam => ({
  key: 'scale',
  label: 'Scale',
  type: 'number',
  min,
  max,
  step: 0.01,
});
const rotation: NumberParam = { key: 'rotation', label: 'Rotation', type: 'number', min: 0, max: 360, step: 1 };
const offsetX: NumberParam = { key: 'offsetX', label: 'Offset X', type: 'number', min: -1, max: 1, step: 0.01 };
const offsetY: NumberParam = { key: 'offsetY', label: 'Offset Y', type: 'number', min: -1, max: 1, step: 0.01 };

const sizingParams: ParamConfig[] = [fit, scaleSizing(), rotation, offsetX, offsetY];

// --- Registry ---

export const shaderRegistry: ShaderEntry[] = [
  // ===== PROCEDURAL =====
  {
    name: 'Mesh Gradient',
    slug: 'mesh-gradient',
    Component: MeshGradient,
    presets: meshGradientPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'distortion', label: 'Distortion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'swirl', label: 'Swirl', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainMixer', label: 'Grain Mixer', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainOverlay', label: 'Grain Overlay', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Smoke Ring',
    slug: 'smoke-ring',
    Component: SmokeRing,
    presets: smokeRingPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'noiseScale', label: 'Noise Scale', type: 'number', min: 0, max: 10, step: 0.1 },
      { key: 'noiseIterations', label: 'Noise Iterations', type: 'number', min: 1, max: 16, step: 1 },
      { key: 'radius', label: 'Radius', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'thickness', label: 'Thickness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'innerShape', label: 'Inner Shape', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Neuro Noise',
    slug: 'neuro-noise',
    Component: NeuroNoise,
    presets: neuroNoisePresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorFront', label: 'Front', type: 'color' },
      { key: 'colorMid', label: 'Mid', type: 'color' },
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'brightness', label: 'Brightness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'contrast', label: 'Contrast', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Dot Orbit',
    slug: 'dot-orbit',
    Component: DotOrbit,
    presets: dotOrbitPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'size', label: 'Size', type: 'number', min: 0, max: 3, step: 0.01 },
      { key: 'sizeRange', label: 'Size Range', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'spreading', label: 'Spreading', type: 'number', min: 0, max: 2, step: 0.01 },
      { key: 'stepsPerColor', label: 'Steps/Color', type: 'number', min: 1, max: 10, step: 1 },
      ...sizingParams,
    ],
  },
  {
    name: 'Dot Grid',
    slug: 'dot-grid',
    Component: DotGrid,
    presets: dotGridPresets,
    requiresImage: false,
    params: [
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorFill', label: 'Fill', type: 'color' },
      { key: 'colorStroke', label: 'Stroke', type: 'color' },
      { key: 'shape', label: 'Shape', type: 'select', options: ['circle', 'diamond', 'square', 'triangle'] },
      { key: 'size', label: 'Size', type: 'number', min: 0, max: 10, step: 0.1 },
      { key: 'gapX', label: 'Gap X', type: 'number', min: 1, max: 100, step: 1 },
      { key: 'gapY', label: 'Gap Y', type: 'number', min: 1, max: 100, step: 1 },
      { key: 'strokeWidth', label: 'Stroke Width', type: 'number', min: 0, max: 5, step: 0.1 },
      { key: 'sizeRange', label: 'Size Range', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'opacityRange', label: 'Opacity Range', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Simplex Noise',
    slug: 'simplex-noise',
    Component: SimplexNoise,
    presets: simplexNoisePresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'stepsPerColor', label: 'Steps/Color', type: 'number', min: 1, max: 10, step: 1 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Metaballs',
    slug: 'metaballs',
    Component: Metaballs,
    presets: metaballsPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'count', label: 'Count', type: 'number', min: 1, max: 20, step: 1 },
      { key: 'size', label: 'Size', type: 'number', min: 0, max: 2, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Waves',
    slug: 'waves',
    Component: Waves,
    presets: wavesPresets,
    requiresImage: false,
    params: [
      { key: 'colorFront', label: 'Front', type: 'color' },
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'shape', label: 'Shape', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'frequency', label: 'Frequency', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'amplitude', label: 'Amplitude', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'spacing', label: 'Spacing', type: 'number', min: 0, max: 3, step: 0.01 },
      { key: 'proportion', label: 'Proportion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Perlin Noise',
    slug: 'perlin-noise',
    Component: PerlinNoise,
    presets: perlinNoisePresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorFront', label: 'Front', type: 'color' },
      { key: 'proportion', label: 'Proportion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'octaveCount', label: 'Octaves', type: 'number', min: 1, max: 8, step: 1 },
      { key: 'persistence', label: 'Persistence', type: 'number', min: 0, max: 2, step: 0.01 },
      { key: 'lacunarity', label: 'Lacunarity', type: 'number', min: 0, max: 4, step: 0.1 },
      ...sizingParams,
    ],
  },
  {
    name: 'Voronoi',
    slug: 'voronoi',
    Component: Voronoi,
    presets: voronoiPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'stepsPerColor', label: 'Steps/Color', type: 'number', min: 1, max: 10, step: 1 },
      { key: 'colorGlow', label: 'Glow Color', type: 'color' },
      { key: 'colorGap', label: 'Gap Color', type: 'color' },
      { key: 'distortion', label: 'Distortion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'gap', label: 'Gap', type: 'number', min: 0, max: 0.2, step: 0.001 },
      { key: 'glow', label: 'Glow', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Warp',
    slug: 'warp',
    Component: Warp,
    presets: warpPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'shape', label: 'Pattern', type: 'select', options: ['checks', 'stripes', 'edge'] },
      { key: 'proportion', label: 'Proportion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'distortion', label: 'Distortion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'swirl', label: 'Swirl', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'swirlIterations', label: 'Swirl Iterations', type: 'number', min: 1, max: 20, step: 1 },
      { key: 'shapeScale', label: 'Shape Scale', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'God Rays',
    slug: 'god-rays',
    Component: GodRays,
    presets: godRaysPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorBloom', label: 'Bloom Color', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 5 },
      { key: 'density', label: 'Density', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'spotty', label: 'Spotty', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'midIntensity', label: 'Mid Intensity', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'midSize', label: 'Mid Size', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'intensity', label: 'Intensity', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'bloom', label: 'Bloom', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Spiral',
    slug: 'spiral',
    Component: Spiral,
    presets: spiralPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorFront', label: 'Front', type: 'color' },
      { key: 'density', label: 'Density', type: 'number', min: 0, max: 5, step: 0.1 },
      { key: 'distortion', label: 'Distortion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'strokeWidth', label: 'Stroke Width', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'strokeTaper', label: 'Stroke Taper', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'strokeCap', label: 'Stroke Cap', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'noise', label: 'Noise', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'noiseFrequency', label: 'Noise Freq', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Swirl',
    slug: 'swirl',
    Component: Swirl,
    presets: swirlPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'bandCount', label: 'Bands', type: 'number', min: 1, max: 20, step: 1 },
      { key: 'twist', label: 'Twist', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'center', label: 'Center', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'proportion', label: 'Proportion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'noiseFrequency', label: 'Noise Freq', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'noise', label: 'Noise', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Dithering',
    slug: 'dithering',
    Component: Dithering,
    presets: ditheringPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorFront', label: 'Front', type: 'color' },
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: ['simplex', 'warp', 'dots', 'wave', 'ripple', 'swirl', 'sphere'],
      },
      { key: 'type', label: 'Type', type: 'select', options: ['random', '2x2', '4x4', '8x8'] },
      { key: 'size', label: 'Size', type: 'number', min: 0.5, max: 20, step: 0.5 },
      ...sizingParams,
    ],
  },
  {
    name: 'Grain Gradient',
    slug: 'grain-gradient',
    Component: GrainGradient,
    presets: grainGradientPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: ['wave', 'dots', 'truchet', 'corners', 'ripple', 'blob', 'sphere'],
      },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'intensity', label: 'Intensity', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'noise', label: 'Noise', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Pulsing Border',
    slug: 'pulsing-border',
    Component: PulsingBorder,
    presets: pulsingBorderPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'roundness', label: 'Roundness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'thickness', label: 'Thickness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'margin', label: 'Margin', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'aspectRatio', label: 'Aspect Ratio', type: 'select', options: ['auto', 'square'] },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'intensity', label: 'Intensity', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'bloom', label: 'Bloom', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'spots', label: 'Spots', type: 'number', min: 1, max: 20, step: 1 },
      { key: 'spotSize', label: 'Spot Size', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'pulse', label: 'Pulse', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'smoke', label: 'Smoke', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'smokeSize', label: 'Smoke Size', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Color Panels',
    slug: 'color-panels',
    Component: ColorPanels,
    presets: colorPanelsPresets,
    requiresImage: false,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'angle1', label: 'Angle 1', type: 'number', min: 0, max: 360, step: 1 },
      { key: 'angle2', label: 'Angle 2', type: 'number', min: 0, max: 360, step: 1 },
      { key: 'length', label: 'Length', type: 'number', min: 0, max: 3, step: 0.01 },
      { key: 'edges', label: 'Edges', type: 'boolean' },
      { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'fadeIn', label: 'Fade In', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'fadeOut', label: 'Fade Out', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'gradient', label: 'Gradient', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'density', label: 'Density', type: 'number', min: 1, max: 20, step: 1 },
      ...sizingParams,
    ],
  },
  {
    name: 'Static Mesh Gradient',
    slug: 'static-mesh-gradient',
    Component: StaticMeshGradient,
    presets: staticMeshGradientPresets,
    requiresImage: false,
    params: [
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'positions', label: 'Positions', type: 'number', min: 1, max: 10, step: 1 },
      { key: 'waveX', label: 'Wave X', type: 'number', min: 0, max: 4, step: 0.01 },
      { key: 'waveXShift', label: 'Wave X Shift', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'waveY', label: 'Wave Y', type: 'number', min: 0, max: 4, step: 0.01 },
      { key: 'waveYShift', label: 'Wave Y Shift', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'mixing', label: 'Mixing', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainMixer', label: 'Grain Mixer', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainOverlay', label: 'Grain Overlay', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Static Radial Gradient',
    slug: 'static-radial-gradient',
    Component: StaticRadialGradient,
    presets: staticRadialGradientPresets,
    requiresImage: false,
    params: [
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'radius', label: 'Radius', type: 'number', min: 0, max: 2, step: 0.01 },
      { key: 'focalDistance', label: 'Focal Distance', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'focalAngle', label: 'Focal Angle', type: 'number', min: 0, max: 360, step: 1 },
      { key: 'falloff', label: 'Falloff', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'mixing', label: 'Mixing', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'distortion', label: 'Distortion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'distortionShift', label: 'Distort Shift', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'distortionFreq', label: 'Distort Freq', type: 'number', min: 1, max: 30, step: 1 },
      { key: 'grainMixer', label: 'Grain Mixer', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainOverlay', label: 'Grain Overlay', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Paper Texture',
    slug: 'paper-texture',
    Component: PaperTexture,
    presets: paperTexturePresets,
    requiresImage: false,
    params: [
      { key: 'colorFront', label: 'Front', type: 'color' },
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'contrast', label: 'Contrast', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'roughness', label: 'Roughness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'fiber', label: 'Fiber', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'fiberSize', label: 'Fiber Size', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'crumples', label: 'Crumples', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'crumpleSize', label: 'Crumple Size', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'folds', label: 'Folds', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'foldCount', label: 'Fold Count', type: 'number', min: 1, max: 20, step: 1 },
      { key: 'fade', label: 'Fade', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'drops', label: 'Drops', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'seed', label: 'Seed', type: 'number', min: 0, max: 100, step: 0.1 },
      ...sizingParams,
    ],
  },

  // ===== IMAGE-BASED =====
  {
    name: 'Water',
    slug: 'water',
    Component: Water,
    presets: waterPresets,
    requiresImage: true,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorHighlight', label: 'Highlight', type: 'color' },
      { key: 'highlights', label: 'Highlights', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'layering', label: 'Layering', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'edges', label: 'Edges', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'waves', label: 'Waves', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'caustic', label: 'Caustic', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'size', label: 'Size', type: 'number', min: 0.01, max: 7, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Fluted Glass',
    slug: 'fluted-glass',
    Component: FlutedGlass,
    presets: flutedGlassPresets,
    requiresImage: true,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorShadow', label: 'Shadow', type: 'color' },
      { key: 'colorHighlight', label: 'Highlight', type: 'color' },
      {
        key: 'shape',
        label: 'Grid Shape',
        type: 'select',
        options: ['lines', 'linesIrregular', 'wave', 'zigzag', 'pattern'],
      },
      {
        key: 'distortionShape',
        label: 'Distortion Shape',
        type: 'select',
        options: ['prism', 'lens', 'contour', 'cascade', 'flat'],
      },
      { key: 'shadows', label: 'Shadows', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'highlights', label: 'Highlights', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'size', label: 'Size', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'angle', label: 'Angle', type: 'number', min: 0, max: 360, step: 1 },
      { key: 'distortion', label: 'Distortion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'shift', label: 'Shift', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'blur', label: 'Blur', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'edges', label: 'Edges', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'stretch', label: 'Stretch', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainMixer', label: 'Grain Mixer', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainOverlay', label: 'Grain Overlay', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Image Dithering',
    slug: 'image-dithering',
    Component: ImageDithering,
    presets: imageDitheringPresets,
    requiresImage: true,
    params: [
      { key: 'colorFront', label: 'Front', type: 'color' },
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorHighlight', label: 'Highlight', type: 'color' },
      { key: 'type', label: 'Type', type: 'select', options: ['random', '2x2', '4x4', '8x8'] },
      { key: 'size', label: 'Size', type: 'number', min: 0.5, max: 20, step: 0.5 },
      { key: 'colorSteps', label: 'Color Steps', type: 'number', min: 1, max: 7, step: 1 },
      { key: 'originalColors', label: 'Original Colors', type: 'boolean' },
      { key: 'inverted', label: 'Inverted', type: 'boolean' },
      ...sizingParams,
    ],
  },
  {
    name: 'Heatmap',
    slug: 'heatmap',
    Component: Heatmap,
    presets: heatmapPresets,
    requiresImage: true,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'contour', label: 'Contour', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'angle', label: 'Angle', type: 'number', min: 0, max: 360, step: 1 },
      { key: 'noise', label: 'Noise', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'innerGlow', label: 'Inner Glow', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'outerGlow', label: 'Outer Glow', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Bloom',
    slug: 'bloom',
    Component: Bloom,
    presets: bloomPresets,
    requiresImage: true,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colors', label: 'Colors', type: 'colorArray', maxColors: 10 },
      { key: 'bloomSpread', label: 'Bloom Spread', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'petalEmphasis', label: 'Petal Emphasis', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'waveCurvature', label: 'Wave Curvature', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'contour', label: 'Contour', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'noise', label: 'Noise', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 3, step: 0.01 },
      { key: 'innerGlow', label: 'Inner Glow', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'outerGlow', label: 'Outer Glow', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Liquid Metal',
    slug: 'liquid-metal',
    Component: LiquidMetal,
    presets: liquidMetalPresets,
    requiresImage: true,
    params: [
      speed(),
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorTint', label: 'Tint', type: 'color' },
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: ['none', 'circle', 'daisy', 'diamond', 'metaballs'],
      },
      { key: 'repetition', label: 'Repetition', type: 'number', min: 1, max: 10, step: 0.1 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'shiftRed', label: 'Shift Red', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'shiftBlue', label: 'Shift Blue', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'distortion', label: 'Distortion', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'contour', label: 'Contour', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'angle', label: 'Angle', type: 'number', min: 0, max: 360, step: 1 },
      ...sizingParams,
    ],
  },
  {
    name: 'Halftone Dots',
    slug: 'halftone-dots',
    Component: HalftoneDots,
    presets: halftoneDotsPresets,
    requiresImage: true,
    params: [
      { key: 'colorBack', label: 'Background', type: 'color' },
      { key: 'colorFront', label: 'Front', type: 'color' },
      { key: 'grid', label: 'Grid', type: 'select', options: ['square', 'hex'] },
      { key: 'type', label: 'Type', type: 'select', options: ['classic', 'gooey', 'holes', 'soft'] },
      { key: 'size', label: 'Size', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'radius', label: 'Radius', type: 'number', min: 0, max: 3, step: 0.01 },
      { key: 'contrast', label: 'Contrast', type: 'number', min: 0, max: 2, step: 0.01 },
      { key: 'originalColors', label: 'Original Colors', type: 'boolean' },
      { key: 'inverted', label: 'Inverted', type: 'boolean' },
      { key: 'grainMixer', label: 'Grain Mixer', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainOverlay', label: 'Grain Overlay', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainSize', label: 'Grain Size', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
  {
    name: 'Halftone CMYK',
    slug: 'halftone-cmyk',
    Component: HalftoneCmyk,
    presets: halftoneCmykPresets,
    requiresImage: true,
    params: [
      { key: 'colorBack', label: 'Paper', type: 'color' },
      { key: 'colorC', label: 'Cyan', type: 'color' },
      { key: 'colorM', label: 'Magenta', type: 'color' },
      { key: 'colorY', label: 'Yellow', type: 'color' },
      { key: 'colorK', label: 'Black', type: 'color' },
      { key: 'type', label: 'Type', type: 'select', options: ['dots', 'ink', 'sharp'] },
      { key: 'size', label: 'Size', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'contrast', label: 'Contrast', type: 'number', min: 0, max: 2, step: 0.01 },
      { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'gridNoise', label: 'Grid Noise', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'floodC', label: 'Flood C', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'floodM', label: 'Flood M', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'floodY', label: 'Flood Y', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'floodK', label: 'Flood K', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'gainC', label: 'Gain C', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'gainM', label: 'Gain M', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'gainY', label: 'Gain Y', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'gainK', label: 'Gain K', type: 'number', min: -1, max: 1, step: 0.01 },
      { key: 'grainSize', label: 'Grain Size', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainMixer', label: 'Grain Mixer', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'grainOverlay', label: 'Grain Overlay', type: 'number', min: 0, max: 1, step: 0.01 },
      ...sizingParams,
    ],
  },
];

export const proceduralShaders = shaderRegistry.filter((s) => !s.requiresImage);
export const imageShaders = shaderRegistry.filter((s) => s.requiresImage);
